default:
  "temp_file_path": "/g/data/dp9/km0642/learning/nci_report/log"
  "archive": "/g/data/dp9/km0642/learning/nci_report/archive"

scratch:
  - dx2
  - qa11
  - hd50
  - tp28
  - dp9
  - hc46
  - er4
  - er8

gdata:
  - dx2
  - qa11  
  - hd50
  - tp28
  - ig2
  - dp9
  - ig2_w
  - er4
  - er8

compute:
  - dx2
  - hd50
  - tp28
  - dp9
  - hc46
  - er4
  - er8