default:
  "temp_file_path": "/g/data/vx53/km0642/log"
  "archive": "/g/data/vx53/km0642/archive"
  "data_stroage": "/g/data/vx53/km0642/data"
  "db_file": "/g/data/vx53/km0642/db/ncireport.db"

scratch:
  - dx2
  - qa11
  - hd50
  - tp28
  - dp9
  - hc46
  - er4
  - er8

gdata:
  - dx2
  - qa11  
  - hd50
  - tp28
  - ig2
  - dp9
  - ig2_w
  - er4
  - er8

compute:
  - dx2
  - hd50
  - tp28
  - dp9
  - hc46
  - er4
  - er8